config/routes.rb
Rails.application.routes.draw do
  resources :chomps, only: [:new, :create]
  resources :players, only: [:index]
  post "players/choose_player"

  get 'chomp/choose_fruit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chomp.rb
class Chomp < ApplicationRecord
  belongs_to :player
  belongs_to :fruit
end

app/models/fruit.rb
class Fruit < ApplicationRecord
  has_many :chomps
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :chomps

  def current_score
    self.chomps.joins(:fruit).sum("fruits.score")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chomps_controller.rb
class ChompsController < ApplicationController
  # GET /chomps/new
  def new
    @fruit = Fruit.order(name: :asc)
  end

  # POST /chomps
  def create
    @chomp = Chomp.new(
      player_id: params[:player_id],
      fruit_id: params[:fruit_id],
    )

    @chomp.save

    redirect_to(controller: "home", action: "index")
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @players = Player.includes(chomps: [:fruit]).all.sort_by { |p| -p.current_score }
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  # GET /players
  def index
    @players = Player.all
  end

  def choose_player
    redirect_to(controller: "chomps", action: "new", player_id: params[:player_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chomps_helper.rb
module ChompsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/chomps/new.html.erb
<h1>Choose fruit</h1>
<div class="layout__divider rainbow-bg"></div>
<form action="<%= url_for(action: "create") %>" method="post">
  <input type="hidden" name="player_id" value="<%= params[:player_id] %>" />
  <div class="mb-3">
    <% @fruit.each do |fruit| %>
      <div class="mb-2">
        <input type="radio" id="<%= fruit.id %>" name="fruit_id" value="<%= fruit.id %>">
        <label for="<%= fruit.id %>"><%= fruit.emoji + " " + fruit.name %></label>
      </div>
    <% end %>
  </div>
  <button class="button" type="submit">Chomp!</button>
</form>

app/views/home/index.html.erb
<h1>Eat some fruit</h1>
<div class="layout__divider rainbow-bg"></div>
<div class="mb-3">
  <%= link_to("Chomp 🌈", players_path, class: "button") %>
</div>
<h2>This week</h2>
<% @players.each_with_index do |player, i|%>
  <div class="text-lg">
    <span class="<%= i == 0 ? 'text-bold' : '' %>"><%= player.name %></span>
    <span>
      <% player.chomps.each do |chomp| %>
        <%= chomp.fruit.emoji %>
      <% end%>
    </span>
  </div>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍇</text></svg>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;700&display=swap" rel="stylesheet"> 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>Choose player</h1>
<div class="layout__divider rainbow-bg"></div>
<form action="<%= url_for(action: "choose_player") %>" method="post">
  <div class="mb-3">
    <% @players.each do |player| %>
      <div class="mb-2">
        <input type="radio" id="<%= player.id %>" name="player_id" value="<%= player.id %>">
        <label for="<%= player.id %>"><%= player.name %></label>
      </div>
    <% end %>
  </div>
  <button class="button" type="submit">Next 🌈</button>
</form>